# Generated by Django 4.1.7 on 2023-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
                ('eaten', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('slept', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
