# Generated by Django 4.1.7 on 2023-02-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.IntegerField(blank=True)),
                ('eaten', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('eaten_report', models.CharField(blank=True, default='none', max_length=200)),
                ('slept', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('slept_report', models.CharField(blank=True, default='none', max_length=200)),
                ('active', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('kid_fight', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('fight_report', models.CharField(blank=True, default='none', max_length=200)),
                ('health_problem', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('health_problem_report', models.CharField(blank=True, default='none', max_length=200)),
                ('toilet', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('toilet_report', models.CharField(blank=True, default='none', max_length=200)),
                ('class_participation', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10)),
                ('class_participation_report', models.CharField(blank=True, default='none', max_length=200)),
                ('kid_attitude', models.CharField(blank=True, default='NONE', max_length=200)),
                ('academic_performance', models.CharField(blank=True, default='NONE', max_length=200)),
                ('kid_interest', models.CharField(blank=True, default='NONE', max_length=200)),
                ('teacher_name', models.CharField(blank=True, default='NONE', max_length=30)),
                ('general_comment', models.CharField(blank=True, default='NONE', max_length=300)),
            ],
        ),
    ]
