# Generated by Django 4.1.7 on 2023-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwsmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='eaten',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='SELECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='slept',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='SELECT', max_length=10),
        ),
    ]
